@echo off
echo Starting backend...
start cmd /k "cd backend && mvnw.cmd spring-boot:run"
echo Waiting for backend to initialize...
timeout /t 10 /nobreak
echo Installing UI dependencies...
cd ui && call npm install
cd ..
echo Starting UI...
start cmd /k "cd ui && npm start"
cd ..
echo Application startup complete!
